type AdminUserModelType = {
  id?: string;
  address?: string;
  emailAddress?: string;
  firstName?: string;
  enabled?: boolean;
  lastName?: string;
  password?: string;
  phoneNumber?: string;
  picture?: string;
  roles?: 'user' | 'seller';
  username?: string;
  // postalCode?: { type?: number | string};
  postalCode?: number;
  description?: string;
  dniPicture?: string;
  bannerDesktop?: string;
  bannerMobile?: string;
  userQualification?: number;
  sellerQualification?: number;
  userTotalQualifications?: number;
  sellerTotalQualifications?: number;
  hasFirstSale?: { type?: boolean; default?: false };
  hasFirstVisitVendor?: { type?: boolean; default?: false };
  balance?: number;
  gift?: number;
  referredBy?: string;
  referrerUsedTheDrop?: boolean;
  extraRouletteDrop?: number;
  firstRoulettePlay?: boolean;
  country?: CountryModelType;
  verificationSms?: boolean;
  discountCodes?: string[];
  createdAt?: string;
  updatedAt?: string;
  city?: string;
  province?: string;
};
