export const AUTH = {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_USER: 'SET_USER',
};

export const COUNTRY = {
  SET_COUNTRY: 'COUNTRY_SET_COUNTRY',
};

export const VENTAS = {
  SET_VALUES: 'SET_VALUES',
  SET_ORDERS: 'SET_ORDERS',
  SET_STATUS: 'SET_STATUS',
  SET_SEARCH: 'SET_SEARCH',
  SET_PERIOD: 'SET_PERIOD',
};

export const LOADS = {
  SET_VALUES: 'SET_VALUES',
  SET_LOADS: 'SET_LOADS',
  SET_STATUS: 'SET_STATUS',
  SET_SEARCH: 'SET_SEARCH',
  SET_PERIOD: 'SET_PERIOD',
};
