export const AUTH = {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_USER: 'SET_USER',
  // SIGNUP_USER: 'SIGNUP_USER',
  // SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
  // SIGNUP_USER_FAILURE: 'SIGNUP_USER_FAILURE',
};

export const CART = {
  SET_VALUE: 'CART_SET_VALUE',
  SET_DISCOUNT: 'CART_SET_DISCOUNT',
  SET_CARTS: 'CART_SET_CARTS',
};

export const COUNTRY = {
  SET_COUNTRY: 'COUNTRY_SET_COUNTRY',
};

export const PAYMENT = {
  SET_PAYMENT: 'PAYMENT_SET_PAYMENT',
};

export const CATEGORY = {
  SET_CATEGORY: 'CATEGORY_SET_CATEGORY',
};

export const GAME = {
  SET_VALUE: 'GAME_SET_VALUE',
  SET_GAMES: 'GAME_SET_GAMES',
};

export const CATALOG = {
  SET_VALUE: 'CATALOG_SET_VALUE',
  SET_COUNTS: 'CATALOG_SET_COUNTS',
  SET_FILTER: 'CATALOG_SET_FILTER',
  ADD_PRODUCTS: 'CATALOG_ADD_PRODUCTS',
  EVERYTHING_LOADED: 'EVERYTHING_LOADED',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
  RESET_PAGE: 'RESET_PAGE',
  INCREMENT_PAGE: 'INCREMENT_PAGE',
  SET_MAX_PRICE: 'SET_MAX_PRICE',
};

export const PLATFORM = {
  SET_PLATFORM: 'PLATFORM_SET_PLATFORMS',
};

export const HOME = {
  SET_VALUE: 'HOME_SET_VALUE',
  SET_RECOMMEND: 'HOME_SET_RECOMMEND',
  SET_FEATURE: 'HOME_SET_FEATURE',
  SET_DISCOUNT: 'HOME_SET_DISCOUNT',
  SET_GAME: 'HOME_SET_GAME',
  SET_PRODUCT: 'HOME_SET_PRODUCT',
  SET_BANNERS: 'HOME_SET_BANNERS',
  SET_CATEGORY: 'HOME_SET_CATEGORY',
};

export const ROULETTE = {
  SET_VALUE: 'ROULETTE_SET_VALUE',
  CAN_PLAY: 'ROULETTE_SET_CAN_PLAY',
  HISTORY: 'ROULETTE_SET_HISTORY',
};

export const PAYMENT_METHOD = {
  SET_VALUE: 'PAYMENT_METHOD_SET_VALUE',
};

export const NOTIFICATION = {
  RECEIVE_NOTIFICATION: 'NOTIFICATION_RECEIVE_NOTIFICATION',
  SET_NOTIFICATION_LIST: 'NOTIFICATION_SET_NOTIFICATION_LIST',
};

export const HEADER = {
  SET_SEARCH: 'HEADER_SET_SEARCH',
};

export const REFERREDBY = {
  SET_REFERREDBY: 'REFERREDBY_SET_REFERREDBY',
};
